d3.select('svg').selectAll('image')
  .data(enemies, function(d){ return d.id; })
  .enter()
  .append('image')
  .attr('class', 'enemy')
  .attr('height', asteroidSize)
  .attr('width', asteroidSize)
  .attr('xlink:href', 'asteroid.png')
  .attr('x', function(d){ return d.x;})
  .attr('y', function(d){ return d.y;})

d3.select('svg').selectAll('image')
  .data([{id: 'player', x: boardWidth / 2, y: boardHeight / 2}], function(d){ return d.id; })
  .enter()
  .append('image')
  .attr('class', 'player')
  .attr('height', '75px')
  .attr('width', '75px')
  .attr('xlink:href', 'player.png')
  .attr('x', function(d){ return d.x;})
  .attr('y', function(d){ return d.y;})
  .call(drag);